### ISSUE TITLE
Bot not applying to any job 

### ISSUE THREAD

**Issue by waqaramjad** [GodsScion/Auto_job_applier_linkedIn#11]
Gettintg this error: 

Failed to find Job listings!
In Applier
Message: no such element: Unable to locate element: {"method":"css selector","selector":".job-card-list__title"}

**Comment by Neurofunk9** [comment]
I have the same issue

Failed to find Job listings!
In Applier
Message: no such element: Unable to locate element: {"method":"css selector","selector":".job-card-list__title"}
  (Session info: chrome=128.0.6613.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x002F8213+26163]
        (No symbol) [0x00289CC4]
        (No symbol) [0x001824C3]
        (No symbol) [0x001C7453]
        (No symbol) [0x001C762B]
        (No symbol) [0x001BD531]
        (No symbol) [0x001EAD04]
        (No symbol) [0x001BD445]
        (No symbol) [0x001EAF54]
        (No symbol) [0x00204661]
        (No symbol) [0x001EAA56]
        (No symbol) [0x001BBE89]
        (No symbol) [0x001BC8CD]
        GetHandleVerifier [0x005CD313+2996019]
        GetHandleVerifier [0x00621B89+3342249]
        GetHandleVerifier [0x00387AEF+614159]
        GetHandleVerifier [0x0038F17C+644508]
        (No symbol) [0x002927FD]
        (No symbol) [0x0028F6F8]
        (No symbol) [0x0028F895]
        (No symbol) [0x00281C16]
        BaseThreadInitThunk [0x76CE7BA9+25]
        RtlInitializeExceptionChain [0x77E4C10B+107]
        RtlClearBits [0x77E4C08F+191]
        (No symbol) [0x00000000]

2024-09-05 23:25:44.507385
########################################################################################################################

Sleeping for 10 min...
Few more min... Gonna start with in next 5 min...

**Comment by GodsScion** [comment]
Please let me know if the latest code is giving you the same error. Also, your current country, might be LinkedIn is serving different html page for your respective locations.

**Comment by ding25y** [comment]
I am getting this error using latest code. I'm located in the U.S.

**Comment by GodsScion** [comment]
Should be fixed in ℹ️ Version: 2024.11.28.16.00 Stable

**Comment by LilLuKaK** [comment]
Error still happening to me:

Trying to Apply to "Programador full stack | CIC Consulting Informátic" job. Job ID: 4122035410
Failed to calculate the date posted!
Message: no such element: Unable to locate element: {"method":"xpath","selector":".//span[contains(normalize-space(), " ago")]"}
  (Session info: chrome=132.0.6834.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x005F74A3+25091]
        (No symbol) [0x0057DC04]
        (No symbol) [0x0045B373]
        (No symbol) [0x0049F4DC]
        (No symbol) [0x0049F65B]
        (No symbol) [0x00494F21]
        (No symbol) [0x004C1F54]
        (No symbol) [0x00494E44]
        (No symbol) [0x004C21A4]
        (No symbol) [0x004DB49E]
        (No symbol) [0x004C1CA6]
        (No symbol) [0x004931D5]
        (No symbol) [0x0049435D]
        GetHandleVerifier [0x008F07C3+3142947]
        GetHandleVerifier [0x00901A2B+3213195]
        GetHandleVerifier [0x008FC412+3191154]
        GetHandleVerifier [0x00698720+685184]
        (No symbol) [0x00586E1D]
        (No symbol) [0x00583E18]
        (No symbol) [0x00583FB6]
        (No symbol) [0x005766F0]
        BaseThreadInitThunk [0x763EFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x771E809E+286]
        RtlGetAppContainerNamedObjectPath [0x771E806E+238]

Im from Spain
